name: apod
description: "A nasa api apod project"

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  multiple_result: ^5.1.0
  flutter_localizations:
    sdk: flutter
  intl: any
  cached_network_image: ^3.4.1
  video_player: ^2.9.2
  youtube_player_flutter: ^9.1.1
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  path_provider: ^2.1.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  focus_detector: ^2.0.1
  home_widget: ^0.7.0
  skeletonizer: ^1.4.3
  translator: ^1.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
